Repository sebgroup/react-components, pull requests merged in 2019-11, with the labels that each got.

#80 Bug/slider negative values
  develop/components/pages/SliderPage.tsx
  docs/js/31.bundle.js
  package-lock.json
  package.json
  src/Slider/Slider.test.tsx
  src/Slider/Slider.tsx
  src/Slider/readme.md
  src/Slider/slider-style.scss
  src/TextBox/TextBox.tsx
  src/TextBoxGroup/TextBoxGroup.tsx
  src/__utils/animations.test.tsx
  src/__utils/animations.tsx
  src/__utils/randomId.test.ts
  src/__utils/randomId.ts
Labels: bug, enhancement

#87 perf(accordion): enhanced accordion by removing repetitive code
  src/Accordion/Accordion.tsx
  src/Accordion/accordion-style.scss
Labels: enhancement

#91 feat(dialogue): improve dialogue
  develop/components/pages/DialoguePage.tsx
  docs/app.js
  docs/js/0.bundle.js
  docs/js/1.bundle.js
  docs/js/10.bundle.js
  docs/js/11.bundle.js
  docs/js/12.bundle.js
  docs/js/13.bundle.js
  docs/js/14.bundle.js
  docs/js/15.bundle.js
  docs/js/16.bundle.js
  docs/js/17.bundle.js
  docs/js/18.bundle.js
  docs/js/19.bundle.js
  docs/js/2.bundle.js
  docs/js/20.bundle.js
  docs/js/21.bundle.js
  docs/js/22.bundle.js
  docs/js/23.bundle.js
  docs/js/24.bundle.js
  docs/js/25.bundle.js
  docs/js/26.bundle.js
  docs/js/27.bundle.js
  docs/js/28.bundle.js
  docs/js/29.bundle.js
  docs/js/30.bundle.js
  docs/js/31.bundle.js
  docs/js/32.bundle.js
  docs/js/33.bundle.js
  docs/js/34.bundle.js
  docs/js/35.bundle.js
  docs/js/36.bundle.js
  docs/js/37.bundle.js
  docs/js/38.bundle.js
  docs/js/39.bundle.js
  docs/js/4.bundle.js
  docs/js/40.bundle.js
  docs/js/41.bundle.js
  docs/js/42.bundle.js
  docs/js/5.bundle.js
  docs/js/6.bundle.js
  docs/js/7.bundle.js
  docs/js/8.bundle.js
  docs/js/9.bundle.js
  src/Dialogue/Dialogue.test.tsx
  src/Dialogue/Dialogue.tsx
  src/Dialogue/dialogue-style.scss
  src/Dialogue/readme.md
Labels: enhancement

#93 Hotfix/dialogue disabled styles
  docs/js/12.bundle.js
  src/Dialogue/Dialogue.test.tsx
  src/Dialogue/Dialogue.tsx
  src/Dialogue/dialogue-style.scss
  src/Dialogue/readme.md
Labels: bug

#68 Enhancement/accordion with ref
  src/Accordion/Accordion.tsx
  src/Accordion/accordion-style.scss
Labels: bug
