Repository sebgroup/react-components, pull requests merged in 2020-03, with the labels that each got.

#152 test(table): fix table tests
  src/Table/Table.test.tsx
Labels: bug

#149 Feature/prettier
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  tslint.json
Labels: dependencies, documentation, enhancement, refactor

#163 fix: sanitize package lock
  package-lock.json
  package.json
Labels: bug

#165 feat(table): switching from hardcoded arrow style to css
  src/Table/Table.tsx
  src/Table/table-style.scss
Labels: enhancement

#153 feat(table-component): add filter feature for table
  develop/components/pages/TablePage.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/readme.md
  src/Table/table-style.scss
Labels: enhancement

#184 Create build-check.yml
  build-check.yml
Labels: CI/CD

#190 Update .travis.yml
  .travis.yml
Labels: CI/CD

#186 Bugs/fix all rows
  src/Table/Table.test.tsx
  src/Table/Table.tsx
Labels: bug

#189 Feature/inline text box
  develop/components/pages/TablePage.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/table-style.scss
Labels: enhancement
