Repository sebgroup/react-components, pull requests merged in 2020-05, with the labels that each got.

#164 Chore/add slider alternative style
  develop/components/pages/SliderPage.tsx
  src/Image/image-style.scss
  src/Slider/Slider.tsx
  src/Slider/readme.md
  src/Slider/slider-style.scss
Labels: 🔨 Enhancement

#351 chore: updating dependencies
  package-lock.json
  package.json
Labels: 📦 Dependencies

#314 Refactor/carousel
  develop/components/App.tsx
  develop/components/pages/CarouselPage.tsx
  package-lock.json
  package.json
  src/Carousel/Carousel.test.tsx
  src/Carousel/Carousel.tsx
  src/Carousel/CarouselIndicators.test.tsx
  src/Carousel/CarouselIndicators.tsx
  src/Carousel/CarouselItem.test.tsx
  src/Carousel/CarouselItem.tsx
  src/Carousel/CarouselNavs.test.tsx
  src/Carousel/CarouselNavs.tsx
  src/Carousel/carousel-style.scss
  src/Carousel/carousel.scss
  src/Carousel/index.ts
  src/Carousel/readme.md
  webpack.config.js
Labels: 🚧 Refactor

#362 Feat/indexes generator
  .prettierignore
  develop/version.json
  package.json
  src/__utils/index.js
  src/index.js
  src/index.json
  tsconfig.json
  utils/indexer.js
  utils/indexer.ts
  webpack.config.js
Labels: 🔨 Enhancement

#366 fix: fix app router invalid import
  develop/components/App.tsx
  develop/index.tsx
  package-lock.json
  package.json
  src/Tooltip/Tooltip.tsx
  src/__utils/Overlay/Overlay.tsx
  src/index.json
Labels: 🐛 Bug

#367 Update Button.tsx
  src/Button/Button.tsx
  src/Button/readme.md
Labels: 🐛 Bug

#368 New Release: Bug fixes and improvements
  .prettierignore
  develop/components/App.tsx
  develop/components/pages/SliderPage.tsx
  develop/index.tsx
  develop/version.json
  package-lock.json
  package.json
  src/Button/Button.tsx
  src/Button/readme.md
  src/Image/image-style.scss
  src/Pagination/Pagination.tsx
  src/Slider/Slider.tsx
  src/Slider/readme.md
  src/Slider/slider-style.scss
  src/Tooltip/Tooltip.tsx
  src/__utils/Overlay/Overlay.tsx
  src/__utils/Overlay/placement.ts
  src/index.js
  src/index.json
  tsconfig.json
  utils/indexer.js
  utils/indexer.ts
  webpack.config.js
Labels: 🚀 Release

#377 refactor: cleaning up develop and docs
  develop/contentindex.json
  develop/index.dev.html
  develop/index.html
  develop/targetindex.json
  package-lock.json
  package.json
  webpack.config.js
Labels: 🚧 Refactor

#371 Refactor/checkbox
  develop/assets/components-list.json
  develop/components/pages/ButtonGroupPage.tsx
  develop/components/pages/ButtonPage.tsx
  develop/components/pages/CheckBoxPage.tsx
  develop/components/pages/FeedbackIndicatorPage.tsx
  develop/components/pages/SliderPage.tsx
  develop/components/pages/TooltipPage.tsx
  develop/styles/shared/route-template.scss
  package-lock.json
  src/CheckBox/CheckBox.test.tsx
  src/CheckBox/CheckBox.tsx
  src/CheckBox/check-box-style.scss
  src/CheckBox/checkbox.scss
  src/CheckBox/readme.md
  src/FeedbackIndicator/FeedbackIndicator.test.tsx
  src/FeedbackIndicator/FeedbackIndicator.tsx
  src/FeedbackIndicator/feedback-indicator.scss
  src/FeedbackIndicator/index.ts
  src/FeedbackIndicator/readme.md
  src/index.json
Labels: 🔨 Enhancement, 🚧 Refactor

#376 Refactor Loader
  develop/components/App.tsx
  develop/components/pages/ButtonPage.tsx
  develop/components/pages/LoaderPage.tsx
  develop/styles/shared/customizations.scss
  src/Button/Button.tsx
  src/Loader/Loader.test.tsx
  src/Loader/Loader.tsx
  src/Loader/loader-style.scss
  src/Loader/loader.scss
  src/Loader/readme.md
Labels: 🚧 Refactor
