Repository sebgroup/react-components, pull requests merged in 2020-04, with the labels that each got.

#212 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#214 feat(table-component): blacklist or hide columns when needed
  develop/components/pages/TablePage.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/readme.md
  src/index.js
Labels: enhancement

#228 Bug/action column bug
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/table-style.scss
Labels: bug

#239 fix(table): fix invalid table component index
  develop/components/pages/TablePage.tsx
  package-lock.json
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/index.ts
Labels: bug

#247 hot fix: fix docs production fail
  README.md
  develop/components/common/TitleBar.tsx
  develop/index.html
  docs/app.js
  docs/index.html
  docs/js/0.bundle.js
  docs/js/1.bundle.js
  docs/js/10.bundle.js
  docs/js/11.bundle.js
  docs/js/12.bundle.js
  docs/js/13.bundle.js
  docs/js/14.bundle.js
  docs/js/15.bundle.js
  docs/js/16.bundle.js
  docs/js/17.bundle.js
  docs/js/18.bundle.js
  docs/js/19.bundle.js
  docs/js/2.bundle.js
  docs/js/20.bundle.js
  docs/js/21.bundle.js
  docs/js/22.bundle.js
  docs/js/23.bundle.js
  docs/js/24.bundle.js
  docs/js/25.bundle.js
  docs/js/26.bundle.js
  docs/js/27.bundle.js
  docs/js/28.bundle.js
  docs/js/29.bundle.js
  docs/js/3.bundle.js
  docs/js/30.bundle.js
  docs/js/31.bundle.js
  docs/js/32.bundle.js
  docs/js/33.bundle.js
  docs/js/34.bundle.js
  docs/js/35.bundle.js
  docs/js/36.bundle.js
  docs/js/37.bundle.js
  docs/js/38.bundle.js
  docs/js/39.bundle.js
  docs/js/4.bundle.js
  docs/js/40.bundle.js
  docs/js/41.bundle.js
  docs/js/42.bundle.js
  docs/js/43.bundle.js
  docs/js/44.bundle.js
  docs/js/45.bundle.js
  docs/js/5.bundle.js
  docs/js/6.bundle.js
  docs/js/7.bundle.js
  docs/js/8.bundle.js
  docs/js/9.bundle.js
  package-lock.json
  package.json
  src/Dialogue/dialogue-style.scss
  webpack.config.js
Labels: bug

#255 Setup Commitlint
  package-lock.json
  package.json
Labels: CI/CD, High Priority

#256 Create gh-pages.yml
  .github/workflows/gh-pages.yml
Labels: 📚 Documentation, 🚀 CI/CD

#257 Docs pipeline and commitlint in master
  .github/workflows/gh-pages.yml
  package-lock.json
  package.json
Labels: 🚀 CI/CD

#262 perf(table): replacing namor with lorem-ipsom, remove buffer from table
  develop/__utils/makeData.tsx
  package-lock.json
  package.json
  src/Table/Table.tsx
Labels: 🚧 Refactor

#269 test(table): fix inconsistency of table test runs
  src/Table/Table.test.tsx
Labels: 🐛 Bug

#254 fix(table-component): use a separate data for inline edit
  develop/components/pages/TablePage.tsx
  src/Table/Table.tsx
  src/Table/table-style.scss
Labels: 🐛 Bug, 📚 Documentation

#258 Bug/tooltip bug
  src/Tooltip/Tooltip.test.tsx
  src/Tooltip/Tooltip.tsx
  src/Tooltip/tooltip-style.scss
  src/__utils/Overlay/Overlay.tsx
  src/__utils/Overlay/overlay-style.scss
Labels: 🐛 Bug

#264 Feat/chip
  develop/assets/components-list.json
  develop/components/pages/ChipPage.tsx
  src/Chip/Chip.test.tsx
  src/Chip/Chip.tsx
  src/Chip/chip.scss
  src/Chip/index.ts
  src/Chip/readme.md
  src/index.js
Labels: 🔨 Enhancement

#278 fix(image-holder): cursor-pointer on clickable image
  jest.config.js
  package.json
  src/Image/Image.test.tsx
  src/Image/Image.tsx
  src/Image/image-style.scss
Labels: 🐛 Bug

#283 feat(datepicker): new datepicker config
  develop/components/pages/DatepickerPage.tsx
  src/Datepicker/Datepicker.tsx
Labels: 🔨 Enhancement

#284 Release: add new feature to datepicker
  develop/components/pages/DatepickerPage.tsx
  src/Datepicker/Datepicker.tsx
Labels: 🚀 Released

#290 fix(tooltip): fix position bug if root container is in relative position
  src/__utils/Overlay/placement.ts
Labels: 🐛 Bug

#292 refactor(pagination): set active in dot/nav on child only
  src/Pagination/Pagination.tsx
Labels: 🚧 Refactor

#285 refactor(accordion): refactoring the accordion component
  develop/components/pages/AccordionPage.tsx
  develop/styles/main.scss
  develop/styles/shared/customizations.scss
  develop/styles/shared/route-template.scss
  package.json
  src/Accordion/Accordion.test.tsx
  src/Accordion/Accordion.tsx
  src/Accordion/AccordionItemBody.tsx
  src/Accordion/accordion-style.scss
  src/Accordion/accordion.scss
Labels: 🚧 Refactor

#291 refactor(breadcrumb): refactor breadcrumb
  develop/components/pages/BreadcrumbPage.tsx
  src/Breadcrumb/Breadcrumb.test.tsx
  src/Breadcrumb/Breadcrumb.tsx
  src/Breadcrumb/breadcrumb-style.scss
  src/Breadcrumb/breadcrumb.scss
  src/Breadcrumb/readme.md
Labels: 🚧 Refactor

#296 refactor(icon): icon component is removed in favor of svgr loader
  develop/assets/components-list.json
  develop/assets/icons/bars.svg
  develop/assets/icons/house.svg
  develop/assets/icons/magnifier.svg
  develop/assets/icons/music.svg
  develop/assets/icons/user.svg
  develop/assets/images/ReactLogo.png
  develop/assets/images/icons/seblogo.svg
  develop/assets/images/icons/user.svg
  develop/assets/svgs/seblogo.svg
  develop/components/common/TitleBar.tsx
  develop/components/pages/BreadcrumbPage.tsx
  develop/components/pages/IconPage.tsx
  develop/typings/index.d.ts
  package-lock.json
  package.json
  src/Icon/Icon.test.tsx
  src/Icon/Icon.tsx
  src/Icon/icon-style.scss
  src/Icon/index.ts
  src/Icon/readme.md
  src/index.js
  webpack.config.js
Labels: 🚧 Refactor

#299 refactor(button): refactor button component
  develop/assets/components-list.json
  develop/assets/icons/pencil.svg
  develop/assets/icons/plus.svg
  develop/assets/svgs/sample-container.svg
  develop/components/pages/ButtonGroupPage.tsx
  develop/components/pages/ButtonPage.tsx
  develop/components/pages/ChipPage.tsx
  develop/components/pages/DialoguePage.tsx
  develop/components/pages/LoaderPage.tsx
  develop/components/pages/ModalPage.tsx
  develop/components/pages/NotificationPage.tsx
  develop/components/pages/TablePage.tsx
  src/Button/Button.test.tsx
  src/Button/Button.tsx
  src/Button/button-style.scss
  src/Button/readme.md
  src/ButtonGroup/ButtonGroup.test.tsx
  src/ButtonGroup/ButtonGroup.tsx
  src/ButtonGroup/index.ts
  src/ButtonGroup/readme.md
  src/index.js
Labels: 🚧 Refactor

#307 Refactor/improve accordion and breadcrumb
  develop/components/pages/AccordionPage.tsx
  develop/components/pages/BreadcrumbPage.tsx
  develop/styles/main.scss
  develop/styles/shared/customizations.scss
  develop/styles/shared/route-template.scss
  src/Accordion/Accordion.test.tsx
  src/Accordion/Accordion.tsx
  src/Accordion/AccordionItem.test.tsx
  src/Accordion/AccordionItem.tsx
  src/Accordion/AccordionItemBody.tsx
  src/Accordion/accordion.scss
  src/Accordion/readme.md
  src/Breadcrumb/Breadcrumb.test.tsx
  src/Breadcrumb/Breadcrumb.tsx
  src/Breadcrumb/BreadcrumbItem.test.tsx
  src/Breadcrumb/BreadcrumbItem.tsx
  src/Breadcrumb/breadcrumb.scss
  src/Breadcrumb/index.ts
  src/Breadcrumb/readme.md
  src/__utils/Collapse.test.tsx
  src/__utils/Collapse.tsx
Labels: 🚧 Refactor
