Repository sebgroup/react-components, pull requests merged in 2020-07, with the labels that each got.

#435 fix(modal): fix modal initial state that causes it to glitch
  src/Modal/Modal.tsx
Labels: 🐛 Bug

#434 Hotfix/fix modal initial state
  src/Modal/Modal.tsx
Labels: 🐛 Bug

#441 fix(overlay): fix overlay issue for long list
  src/__utils/Overlay/Overlay.tsx
Labels: 🐛 Bug

#440 refactor(dropdown): hide select all option if list has only one item
  src/Dropdown/Dropdown.tsx
  src/index.json
Labels: 🔨 Enhancement

#442 Minor release
  .gitignore
  develop/components/pages/TablePage.tsx
  package-lock.json
  src/Dropdown/Dropdown.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/table-style.scss
  src/__utils/Overlay/Overlay.tsx
Labels: 🚀 Release

#446 fix(dropdown): to show only all selected in multi mode only
  src/Dropdown/Dropdown.tsx
Labels: 🐛 Bug

#445 fix(tooltip): fix tooltip
  src/Tooltip/Tooltip.test.tsx
  src/__utils/Overlay/Overlay.test.tsx
  src/__utils/Overlay/Overlay.tsx
  src/__utils/Overlay/placement.test.tsx
  src/__utils/Overlay/placement.ts
Labels: 🐛 Bug

#448 New release
  package-lock.json
  src/Dropdown/Dropdown.tsx
  src/Tooltip/Tooltip.test.tsx
  src/__utils/Overlay/Overlay.test.tsx
  src/__utils/Overlay/Overlay.tsx
  src/__utils/Overlay/placement.test.tsx
  src/__utils/Overlay/placement.ts
Labels: 🚀 Release

#449 Feature/table-refactor
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/readme.md
  src/Table/sections/ActionColumnUI.tsx
  src/Table/sections/RowUI.tsx
  src/Table/sections/TableUI.tsx
  src/Table/sections/TextboxGroup.tsx
  src/Table/sections/helperFunctions.ts
  src/Table/table-style.scss
  src/index.json
Labels: 🚧 Refactor
