Repository sebgroup/react-components, pull requests merged in 2020-02, with the labels that each got.

#115 build(bootstrap): upgrades SEB bootstrap
  package-lock.json
  package.json
Labels: dependencies

#114 refactor(button): updates button theme names
  develop/components/pages/ButtonPage.tsx
  src/Button/Button.test.tsx
  src/Button/Button.tsx
  src/Button/button-style.scss
  src/Button/readme.md
Labels: help wanted

#113 dropdown alert style fix
  develop/components/pages/DropdownPage.tsx
  src/Dropdown/Dropdown.tsx
  src/Dropdown/dropdown-style.scss
Labels: bug

#116 Chore/fix audit warnings
  develop/components/common/About.tsx
  develop/components/common/TitleBar.tsx
  develop/components/pages/AccordionPage.tsx
  develop/components/pages/BreadcrumbPage.tsx
  develop/components/pages/ButtonPage.tsx
  develop/components/pages/CarouselPage.tsx
  develop/components/pages/ChartPage.tsx
  develop/components/pages/CheckBoxPage.tsx
  develop/components/pages/DatepickerPage.tsx
  develop/components/pages/DialoguePage.tsx
  develop/components/pages/DropdownPage.tsx
  develop/components/pages/IconPage.tsx
  develop/components/pages/ImageCropperPage.tsx
  develop/components/pages/ImagePage.tsx
  develop/components/pages/InlineLinkPage.tsx
  develop/components/pages/LoaderPage.tsx
  develop/components/pages/ModalPage.tsx
  develop/components/pages/NotificationPage.tsx
  develop/components/pages/PaginationPage.tsx
  develop/components/pages/ProgressBarPage.tsx
  develop/components/pages/RadioButtonPage.tsx
  develop/components/pages/RadioGroupPage.tsx
  develop/components/pages/RatingPage.tsx
  develop/components/pages/SliderPage.tsx
  develop/components/pages/StepTrackerPage.tsx
  develop/components/pages/StepperPage.tsx
  develop/components/pages/TabsPage.tsx
  develop/components/pages/TextAreaPage.tsx
  develop/components/pages/TextBoxGroupPage.tsx
  develop/components/pages/TextBoxPage.tsx
  develop/components/pages/TextLabelPage.tsx
  develop/components/pages/TimelinePage.tsx
  develop/components/pages/TimepickerPage.tsx
  develop/components/pages/TimerPage.tsx
  develop/components/pages/TogglePage.tsx
  develop/components/pages/TooltipPage.tsx
  develop/components/pages/VideoPage.tsx
  package-lock.json
  package.json
  src/Modal/Modal.test.tsx
Labels: dependencies

#73 Feature/table
  develop/__utils/browser.util.ts
  develop/__utils/makeData.tsx
  develop/__utils/queryString.ts
  develop/assets/components-list.json
  develop/components/App.tsx
  develop/components/pages/ModalPage.tsx
  develop/components/pages/TablePage.tsx
  package-lock.json
  package.json
  src/Modal/Modal.test.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/index.ts
  src/Table/readme.md
  src/Table/table-style.scss
  webpack.config.dev.js
  webpack.config.docs.js
Labels: enhancement

#125 fix(accordion): fixes #124
  develop/components/pages/AccordionPage.tsx
  src/Accordion/Accordion.test.tsx
  src/Accordion/Accordion.tsx
  src/Accordion/readme.md
Labels: bug

#134 refactor(table): move and reuse table component
  src/Table/Table.tsx
Labels: refactor

#136 Update README.md
  README.md
Labels: documentation

#99 Refactor/tooltip
  develop/components/pages/TooltipPage.tsx
  develop/tsconfig.json
  src/Tooltip/Tooltip.test.tsx
  src/Tooltip/Tooltip.tsx
  src/Tooltip/readme.md
  src/Tooltip/tooltip-style.scss
  src/__utils/Overlay/Overlay.test.tsx
  src/__utils/Overlay/Overlay.tsx
  src/__utils/Overlay/overlay-style.scss
  src/__utils/Overlay/placement.test.tsx
  src/__utils/Overlay/placement.ts
  tsconfig.json
Labels: bug, enhancement
