Repository sebgroup/react-components, pull requests merged in 2020-06, with the labels that each got.

#396 fix(dropdown): fix dropdown error rendered incorrectly
  develop/components/pages/DropdownPage.tsx
  src/Dropdown/Dropdown.test.tsx
  src/Dropdown/Dropdown.tsx
  src/Dropdown/dropdown-style.scss
  src/index.json
Labels: ❕ High Priority, 🐛 Bug

#392 feat(table): fixes table sorting
  src/Table/Table.tsx
Labels: 🐛 Bug

#420 refactor(toggle): refactor toggle apis
  .vscode/settings.json
  develop/components/pages/DropdownPage.tsx
  develop/components/pages/TogglePage.tsx
  src/CheckBox/CheckBox.tsx
  src/CheckBox/readme.md
  src/Dropdown/Dropdown.test.tsx
  src/Image/DivImage.test.tsx
  src/Modal/Modal.test.tsx
  src/Toggle/Toggle.test.tsx
  src/Toggle/Toggle.tsx
  src/Toggle/readme.md
  src/Toggle/toggle.scss
  src/Tooltip/Tooltip.test.tsx
Labels: 🚧 Refactor

#427 feat(dropdown): add placeholdersConfig attribute to dropdown
  src/Dropdown/Dropdown.test.tsx
  src/Dropdown/Dropdown.tsx
  src/Dropdown/readme.md
Labels: 🔨 Enhancement

#430 New release
  .vscode/settings.json
  develop/components/common/TitleBar.tsx
  develop/components/pages/ModalPage.tsx
  package-lock.json
  package.json
  src/Dropdown/Dropdown.test.tsx
  src/Dropdown/Dropdown.tsx
  src/Dropdown/readme.md
  src/Modal/Modal.test.tsx
  src/Modal/Modal.tsx
  src/Modal/modal.scss
Labels: 🚀 Release
