Repository sebgroup/react-components, pull requests merged in 2020-08, with the labels that each got.

#456 :zap: fixed text overflow by breaking it arbitrarily
  src/Notification/notification-style.scss
Labels: 🐛 Bug

#453 fix(dropdown): fixes a potential issue causing the dropdown toggle bu…
  src/Dropdown/Dropdown.tsx
Labels: 🐛 Bug

#454 perf(overlay): improve performance
  src/__utils/Overlay/Overlay.tsx
  src/index.json
Labels: 🚧 Refactor

#457 fix(pagination): set button type in pagination
  src/Pagination/Pagination.tsx
Labels: 🐛 Bug

#458 A release that mostly fixes button type issue
  package-lock.json
  src/Dropdown/Dropdown.tsx
  src/Notification/notification-style.scss
  src/Pagination/Pagination.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/readme.md
  src/Table/sections/ActionColumnUI.tsx
  src/Table/sections/RowUI.tsx
  src/Table/sections/TableUI.tsx
  src/Table/sections/TextboxGroup.tsx
  src/Table/sections/helperFunctions.ts
  src/Table/table-style.scss
  src/__utils/Overlay/Overlay.tsx
Labels: 🚀 Release

#460 fix(timeline): fix horizontal timeline misalignment
  src/Timeline/Timeline.tsx
  src/Timeline/timeline-style.scss
Labels: ⚠️ Invalid

#461 Release: fixes horizontal timeline misalignment
  src/Timeline/Timeline.tsx
  src/Timeline/timeline-style.scss
Labels: 🚀 Release

#462 feat(modal): add escape to dismiss and focus trap
  develop/components/pages/ModalPage.tsx
  src/Modal/Modal.test.tsx
  src/Modal/Modal.tsx
  src/Modal/modal.scss
Labels: 🔨 Enhancement

#464 Feature/row custom actions column
  develop/__utils/makeData.tsx
  develop/components/pages/TablePage.tsx
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/sections/ActionColumnUI.tsx
  src/Table/sections/RowUI.tsx
  src/Table/sections/TableUI.tsx
Labels: 🔨 Enhancement

#465 Release 27/Aug/2020
  develop/__utils/makeData.tsx
  develop/components/pages/ModalPage.tsx
  develop/components/pages/TablePage.tsx
  src/Modal/Modal.test.tsx
  src/Modal/Modal.tsx
  src/Modal/modal.scss
  src/Table/Table.test.tsx
  src/Table/Table.tsx
  src/Table/sections/ActionColumnUI.tsx
  src/Table/sections/RowUI.tsx
  src/Table/sections/TableUI.tsx
Labels: 🚀 Release
