Repository sebgroup/react-components, pull requests merged in 2020-09, with the labels that each got.

#467 fix(modal): check if event exist before accessing, give ellipsis width
  src/Modal/Modal.tsx
  src/Table/table-style.scss
Labels: 🐛 Bug

#471 Release: Modal undefined error fixes
  package-lock.json
  src/Modal/Modal.tsx
  src/Table/table-style.scss
Labels: 🚀 Release

#475 refactor: change the way window is handled with Gatsby
  src/components/SideMenu.tsx
  src/hooks/useIsMobile.ts
Labels: 🔨 Enhancement
