Repository sebgroup/react-components, pull requests merged in 2020-12, with the labels that each got.

#505 build(removing-deps): removes extraneous dependencies
  package-lock.json
  package.json
Labels: 📦 Dependencies

#506 Refactor/pagination
  lib/jest.config.js
  lib/src/Pagination/NumberedPagination.test.tsx
  lib/src/Pagination/NumberedPagination.tsx
  lib/src/Pagination/Page.test.tsx
  lib/src/Pagination/Page.tsx
  lib/src/Pagination/Pagination.test.tsx
  lib/src/Pagination/Pagination.tsx
  lib/src/Pagination/index.ts
  lib/src/Pagination/pagination-style.scss
  lib/src/Pagination/pagination.scss
  lib/src/Table/Table.test.tsx
  lib/src/Table/table-style.scss
  src/components/Docs.tsx
  src/components/DocsWrapper.tsx
  src/pages/docs/pagination.tsx
  src/pages/docs/table.tsx
Labels: 🚧 Refactor

#503 fix(carousel): fixes timer and css isses with swiping
  lib/src/Carousel/Carousel.tsx
  lib/src/Carousel/CarouselItem.test.tsx
  lib/src/Carousel/CarouselItem.tsx
  lib/src/Carousel/carousel.scss
  src/components/DocsPlaygroud.tsx
  src/pages/docs/carousel.tsx
Labels: 🐛 Bug

#497 refactor(timeline): refactor timeline
  lib/src/Timeline/Timeline.test.tsx
  lib/src/Timeline/Timeline.tsx
  lib/src/Timeline/TimelineItem.test.tsx
  lib/src/Timeline/TimelineItem.tsx
  lib/src/Timeline/index.ts
  lib/src/Timeline/timeline-item.scss
  lib/src/Timeline/timeline-style.scss
  lib/src/Timeline/timeline.scss
  lib/webpack.config.js
  package-lock.json
  src/pages/docs/timeline.tsx
Labels: 🚧 Refactor

#507 Refactor/radio button
  lib/src/RadioButton/RadioButton.test.tsx
  lib/src/RadioButton/RadioButton.tsx
  lib/src/RadioButton/RadioGroup/RadioGroup.test.tsx
  lib/src/RadioButton/RadioGroup/RadioGroup.tsx
  lib/src/RadioButton/RadioGroup/radio-group.scss
  lib/src/RadioButton/RadioGroup/readme.md
  lib/src/RadioButton/index.ts
  lib/src/RadioButton/radio-button.scss
  lib/src/RadioGroup/index.ts
  lib/src/index.json
  lib/src/radiogroup.scss
  src/hooks/useDynamicForm.tsx
  src/pages/docs/radiobutton.tsx
  static/components-list.json
Labels: 🚧 Refactor

#487 feat(toggle-selector): new component
  lib/src/Dropdown/dropdown-style.scss
  lib/src/FeedbackIndicator/FeedbackIndicator.tsx
  lib/src/FeedbackIndicator/feedback-indicator.scss
  lib/src/TextBox/TextBox.tsx
  lib/src/ToggleSelector/ToggleSelector.test.tsx
  lib/src/ToggleSelector/ToggleSelector.tsx
  lib/src/ToggleSelector/ToggleSelectorItem.test.tsx
  lib/src/ToggleSelector/ToggleSelectorItem.tsx
  lib/src/ToggleSelector/index.ts
  lib/src/ToggleSelector/toggle-selector-item.scss
  lib/src/ToggleSelector/toggle-selector.scss
  lib/src/index.json
  package-lock.json
  package.json
  src/components/Docs.tsx
  src/components/DocsAPIs.tsx
  src/hooks/useDynamicForm.tsx
  src/pages/docs/toggle-selector.tsx
  src/styles/docs.scss
  static/components-list.json
  static/icons/emoji-dizzy-fill.svg
  static/icons/emoji-laughing-fill.svg
  static/icons/emoji-smile-upside-down-fill.svg
Labels: 🔨 Enhancement

#483 refactor(video): remove resource type
  lib/src/Video/Video.test.tsx
  lib/src/Video/Video.tsx
  lib/src/Video/api-mapper.ts
  lib/src/Video/types-definition.ts
  src/pages/docs/video.tsx
  src/utils/api-parser.ts
Labels: 🚧 Refactor
