Repository sebgroup/react-components, pull requests merged in 2021-09, with the labels that each got.

#649 refactor(package-lock): fix merge conflict
  lib/src/Tooltip/Tooltip.test.tsx
  lib/src/Tooltip/useOverlay.test.tsx
  package-lock.json
Labels: 🚧 Refactor

#650 feat(dynamic-forms): adds warning messages
  docs/src/pages/docs/dynamic-forms.tsx
  lib/src/hooks/useDynamicForm.test.tsx
  lib/src/hooks/useDynamicForm.tsx
Labels: 🐛 Bug, 🔨 Enhancement

#651 docs(gh-pages): fix documentation version dropdown
  .github/workflows/gh-pages.yml
Labels: 📚 Documentation

#657 Feature/dynamic form info
  lib/src/hooks/useDynamicForm.tsx
Labels: 🔨 Enhancement

#661 fix(overlay): fix overlay styling issue
  lib/src/Tooltip/overlay.scss
  lib/src/index.json
Labels: 🐛 Bug
