Repository sebgroup/react-components, pull requests merged in 2021-12, with the labels that each got.

#677 refactor(carousel): improve structure
  .github/CODEOWNERS
  docs/src/pages/docs/carousel.tsx
  lib/src/Carousel/Carousel.tsx
  lib/src/Carousel/CarouselIndicators.tsx
  lib/src/Carousel/CarouselItem.tsx
  lib/src/Carousel/CarouselNavs.test.tsx
  lib/src/Carousel/CarouselNavs.tsx
  lib/src/Carousel/carousel.scss
Labels: 🚧 Refactor

#680 refactor(datepicker): improve accessibility
  docs/src/pages/docs/datepicker.tsx
  lib/src/Datepicker/Datepicker.test.tsx
  lib/src/Datepicker/Datepicker.tsx
Labels: 🔨 Enhancement, 🚧 Refactor

#676 refactor(timer): refactor timer
  lib/src/Timer/Timer.test.tsx
  lib/src/Timer/Timer.tsx
Labels: 🚧 Refactor

#674 Refactor/toggle selector accessibility
  lib/src/ToggleSelector/ToggleSelector.tsx
Labels: 🚧 Refactor

#672 refactor(video): add title tag to improve accessibility
  docs/src/pages/docs/video.tsx
  lib/src/Video/Video.tsx
  lib/src/Video/types-definition.ts
Labels: 🚧 Refactor

#671 refactor(toggle): remove redundant default role set
  lib/src/Toggle/Toggle.tsx
Labels: 🚧 Refactor

#684 refactor(dropdown): improve accessibility
  lib/src/Datepicker/Datepicker.test.tsx
  lib/src/Dropdown/CustomDropdownItem.test.tsx
  lib/src/Dropdown/CustomDropdownItem.tsx
  lib/src/Dropdown/Dropdown.test.tsx
  lib/src/Dropdown/Dropdown.tsx
  lib/src/Dropdown/dropdown.scss
  lib/src/index.json
  lib/src/utils/index.ts
  lib/src/utils/keyboardHelper.test.ts
  lib/src/utils/keyboardHelper.ts
  lib/test/setupTests.js
Labels: 🔨 Enhancement, 🚧 Refactor

#689 refactor(feedback-indicator): improve accessibility
  docs/src/pages/docs/feedbackindicator.tsx
  lib/src/FeedbackIndicator/FeedbackIndicator.tsx
Labels: 🚧 Refactor

#670 refactor(stepper): improve stepper accessibility
  docs/src/pages/docs/stepper.tsx
  lib/src/Stepper/Stepper.test.tsx
  lib/src/Stepper/Stepper.tsx
  lib/src/hooks/useDynamicForm.test.tsx
Labels: 🚧 Refactor

#679 refactor(chip): improve accessibility
  docs/src/pages/docs/chip.tsx
  lib/src/Chip/Chip.test.tsx
  lib/src/Chip/Chip.tsx
Labels: 🔨 Enhancement, 🚧 Refactor

#681 refactor(timeline): improve timeline accessibility
  docs/src/pages/docs/timeline.tsx
  lib/src/Timeline/Timeline.tsx
  lib/src/Timeline/TimelineItem.test.tsx
  lib/src/Timeline/TimelineItem.tsx
Labels: 🚧 Refactor

#682 refactor(table): improve table accessibility
  docs/src/pages/docs/table.tsx
  lib/src/Table/parts/TableRow.tsx
Labels: 🚧 Refactor

#683 refactor(step-tracker): refactor step tracker
  docs/src/pages/docs/steptracker.tsx
  lib/src/StepTracker/StepLabel.tsx
  lib/src/StepTracker/StepTracker.test.tsx
  lib/src/StepTracker/StepTracker.tsx
  lib/src/StepTracker/steplabel.scss
  lib/src/StepTracker/steptracker.scss
Labels: 🚧 Refactor

#685 refactor(slider): improve slider accessibility
  docs/src/pages/docs/slider.tsx
  lib/src/Slider/Slider.test.tsx
  lib/src/Slider/Slider.tsx
  lib/src/Slider/slider.scss
Labels: 🚧 Refactor

#686 docs(progressbar): include accessibility in progressbar doc
  docs/src/pages/docs/progressbar.tsx
Labels: 📚 Documentation

#687 refactor(pagination): improve pagination accessibility
  docs/src/pages/docs/pagination.tsx
  lib/src/Pagination/NumberedPagination.tsx
  lib/src/Pagination/Page.tsx
  lib/src/Pagination/Pagination.tsx
Labels: 🚧 Refactor

#690 refactor(img): improve accessibility
  docs/src/pages/docs/image.tsx
  lib/src/Image/Img.tsx
Labels: 🚧 Refactor
