Repository sebgroup/react-components, pull requests merged in 2021-04, with the labels that each got.

#565 Fix/dynamic form missing labels and descriptions
  docs/src/pages/docs/dynamic-forms.tsx
  lib/src/hooks/useDynamicForm.tsx
  package-lock.json
Labels: 🐛 Bug

#569 Feature/dynamic forms extra props and initial values
  docs/src/pages/docs/button.tsx
  docs/src/pages/docs/buttongroup.tsx
  docs/src/pages/docs/carousel.tsx
  docs/src/pages/docs/checkbox.tsx
  docs/src/pages/docs/datepicker.tsx
  docs/src/pages/docs/dynamic-forms.tsx
  docs/src/pages/docs/image.tsx
  docs/src/pages/docs/loader.tsx
  docs/src/pages/docs/modal.tsx
  docs/src/pages/docs/notification.tsx
  docs/src/pages/docs/radiobutton.tsx
  docs/src/pages/docs/slider.tsx
  docs/src/pages/docs/stepper.tsx
  docs/src/pages/docs/textarea.tsx
  docs/src/pages/docs/textbox.tsx
  docs/src/pages/docs/timeline.tsx
  docs/src/pages/docs/toggle-selector.tsx
  lib/src/hooks/useDynamicForm.tsx
Labels: 🐛 Bug, 📚 Documentation, 🔨 Enhancement

#568 Fix/dropdown disabled and selected options
  lib/src/Dropdown/Dropdown.test.tsx
  lib/src/Dropdown/Dropdown.tsx
  lib/src/Dropdown/dropdown.scss
Labels: 🐛 Bug

#572 fix(datepicker): style specificity
  lib/src/Datepicker/datepicker.scss
Labels: 🐛 Bug

#575 build(build-check): add new task in buildcheck.yaml
  .github/workflows/build-check.yml
Labels: 🐛 Bug

#573 docs(radio-button): fix inline example
  .github/workflows/build-check.yml
  docs/src/pages/docs/radiobutton.tsx
  package-lock.json
Labels: 📚 Documentation

#576 docs(loader): fix initial size in docs
  docs/src/pages/docs/loader.tsx
Labels: 📚 Documentation

#582 fix(stepper): fix the location of the feedback indicator in the stepp…
  lib/src/Stepper/Stepper.tsx
Labels: 🐛 Bug

#583 refactor(overlay): add classname to overlay
  lib/src/Tooltip/Overlay.tsx
Labels: 🔨 Enhancement

#580 feat(dropdown): adds a feedback indicator for dropdown component
  lib/src/Dropdown/Dropdown.tsx
  package-lock.json
Labels: 🔨 Enhancement

#577 Fix/dynamic form options value
  docs/src/pages/docs/dynamic-forms.tsx
  docs/src/pages/docs/steptracker.tsx
  docs/src/pages/docs/textlabel.tsx
  docs/src/pages/docs/toggle.tsx
  docs/src/pages/docs/tooltip.tsx
  docs/src/pages/docs/video.tsx
  docs/src/utils/helpers.ts
  lib/src/hooks/useDynamicForm.tsx
Labels: 🐛 Bug, 📚 Documentation

#581 feat(dynamic-forms): adds error optional messages that can be mapped …
  docs/src/pages/docs/dynamic-forms.tsx
  lib/src/hooks/useDynamicForm.tsx
  package-lock.json
Labels: 🔨 Enhancement

#578 docs(build): build using npm7
  .github/workflows/build-check.yml
  .github/workflows/gh-pages.yml
  .github/workflows/publish.yml
  docs/gatsby-config.js
  docs/gatsby-node.js
  docs/package-lock.json
  docs/package.json
  docs/src/utils/api-parser.ts
  lib/package-lock.json
  package-lock.json
  package.json
Labels: 📚 Documentation, 🚀 CI/CD

#588 add missing usage of wrapper props in textbox
  lib/src/Textbox/Textbox.tsx
  lib/src/index.json
Labels: 🐛 Bug

#590 Feature/dynamic form wrapping element
  docs/src/pages/docs/checkbox.tsx
  docs/src/pages/docs/datepicker.tsx
  docs/src/pages/docs/dynamic-forms.tsx
  docs/src/pages/docs/image.tsx
  docs/src/pages/docs/slider.tsx
  docs/src/pages/docs/stepper.tsx
  docs/src/pages/docs/textarea.tsx
  docs/src/pages/docs/textbox.tsx
  docs/src/pages/docs/toggle-selector.tsx
  lib/src/hooks/useDynamicForm.tsx
  lib/src/index.json
Labels: 🔨 Enhancement

#595 docs(images): fix broken documentation images
  docs/src/pages/docs/carousel.tsx
  docs/src/pages/docs/image.tsx
  docs/static/images/painting-1.jpg
  docs/static/images/painting-2.jpg
  docs/static/images/painting-3.jpg
  docs/static/images/painting-4.jpg
  docs/static/images/rabbit-on-the-spot.jpg
  package-lock.json
Labels: 🐛 Bug
