Repository sebgroup/react-components, pull requests merged in 2021-03, with the labels that each got.

#536 build(yml): update workflow yaml
  .github/workflows/build-check.yml
  .github/workflows/gh-pages.yml
  .github/workflows/publish.yml
  src/index.json
Labels: 🚀 CI/CD

#534 fix(dropdown): remove conditionally added hooks
  lib/src/Dropdown/Dropdown.tsx
Labels: 🐛 Bug

#535 improve build
  docs/package-lock.json
  docs/package.json
  docs/src/pages/docs/table.tsx
  lib/package-lock.json
  lib/package.json
  lib/rollup.config.js
  lib/scripts/indexer.js
  lib/scripts/post-build.js
  lib/src/Pagination/NumberedPagination.tsx
  lib/src/Pagination/Pagination.tsx
  lib/src/Table/Table.tsx
  lib/src/Table/parts/TableBody.test.tsx
  lib/src/Table/parts/TableBody.tsx
  lib/src/Table/parts/TableCell.test.tsx
  lib/src/Table/parts/TableCell.tsx
  lib/src/Table/parts/TableHeader.test.tsx
  lib/src/Table/parts/TableHeader.tsx
  lib/src/Table/parts/TableHeaderCell.test.tsx
  lib/src/Table/parts/TableHeaderCell.tsx
  lib/src/Table/parts/TableRow.test.tsx
  lib/src/Table/parts/TableRow.tsx
  lib/src/Timeline/timeline-item.scss
  lib/src/Tooltip/Tooltip.tsx
  lib/src/index.json
  lib/src/index.ts
  lib/webpack.config.js
  package-lock.json
  package.json
Labels: 🔨 Enhancement

#529 fix: fix tslib build and test fail
  lib/src/Carousel/Carousel.test.tsx
  lib/src/Image/Img.test.tsx
  lib/src/Notification/Notification.test.tsx
  lib/src/Tooltip/placement.ts
  lib/tsconfig.json
  package-lock.json
  package.json
Labels: 🐛 Bug

#533 Update pipelines
  .github/workflows/build-check.yml
  .github/workflows/gh-pages.yml
  .github/workflows/publish.yml
  lib/src/Datepicker/Datepicker.test.tsx
Labels: 🚀 CI/CD

#537 docs(techstack): fix static image url
  .github/workflows/build-check.yml
  .github/workflows/gh-pages.yml
  .github/workflows/publish.yml
  docs/gatsby-config.js
  docs/package.json
  docs/src/components/TechStack.tsx
  docs/src/pages/index.tsx
  package-lock.json
  package.json
Labels: 📚 Documentation, 🚀 CI/CD

#539 Develop
  .github/workflows/publish.yml
  docs/src/components/TechStack.tsx
  docs/src/pages/index.tsx
  lib/src/Carousel/Carousel.test.tsx
  lib/src/Datepicker/Datepicker.test.tsx
  lib/src/Image/Img.test.tsx
  lib/src/Notification/Notification.test.tsx
  lib/src/Tooltip/placement.ts
  lib/tsconfig.json
  package-lock.json
  package.json
Labels: 🐛 Bug

#542 Feature/move dynamic form to lib
  docs/src/pages/docs/accordion.tsx
  docs/src/pages/docs/breadcrumb.tsx
  docs/src/pages/docs/button.tsx
  docs/src/pages/docs/buttongroup.tsx
  docs/src/pages/docs/carousel.tsx
  docs/src/pages/docs/checkbox.tsx
  docs/src/pages/docs/closebutton.tsx
  docs/src/pages/docs/datepicker.tsx
  docs/src/pages/docs/dropdown.tsx
  docs/src/pages/docs/feedbackindicator.tsx
  docs/src/pages/docs/image.tsx
  docs/src/pages/docs/imagecropper.tsx
  docs/src/pages/docs/loader.tsx
  docs/src/pages/docs/modal.tsx
  docs/src/pages/docs/notification.tsx
  docs/src/pages/docs/pagination.tsx
  docs/src/pages/docs/progressbar.tsx
  docs/src/pages/docs/radiobutton.tsx
  docs/src/pages/docs/rating.tsx
  docs/src/pages/docs/slider.tsx
  docs/src/pages/docs/stepper.tsx
  docs/src/pages/docs/steptracker.tsx
  docs/src/pages/docs/table.tsx
  docs/src/pages/docs/textarea.tsx
  docs/src/pages/docs/textbox.tsx
  docs/src/pages/docs/textlabel.tsx
  docs/src/pages/docs/timeline.tsx
  docs/src/pages/docs/timer.tsx
  docs/src/pages/docs/toggle-selector.tsx
  docs/src/pages/docs/toggle.tsx
  docs/src/pages/docs/tooltip.tsx
  docs/src/pages/docs/video.tsx
  docs/src/utils/helpers.ts
  lib/package.json
  lib/src/hooks/index.ts
  lib/src/hooks/useDynamicForm.tsx
Labels: 🔨 Enhancement

#548 feat(dropdown): adds custom lables for selected item
  lib/src/Dropdown/Dropdown.test.tsx
  lib/src/Dropdown/Dropdown.tsx
Labels: 🔨 Enhancement

#541 Doc/support multi version
  .github/workflows/gh-pages.yml
  docs/gatsby-config.js
  docs/package.json
  docs/src/assets/jsons/versions.json
  docs/src/components/Navbar.tsx
  docs/src/components/SideMenu.tsx
  docs/src/components/VersionsDropdown.tsx
  docs/src/configs.ts
  docs/src/pages/404.tsx
  docs/src/styles/navbar.scss
  docs/src/styles/versions-dropdown.scss
Labels: 📚 Documentation, 🔨 Enhancement, 🚀 CI/CD

#553 fix(button): fix button theme flickering
  lib/src/Button/Button.tsx
Labels: 🐛 Bug

#516 refactor(components): add forward ref
  docs/src/pages/docs/tooltip.tsx
  lib/src/Accordion/Accordion.tsx
  lib/src/Accordion/AccordionItem.tsx
  lib/src/Breadcrumb/Breadcrumb.tsx
  lib/src/Breadcrumb/BreadcrumbItem.tsx
  lib/src/Button/Button.tsx
  lib/src/ButtonGroup/ButtonGroup.tsx
  lib/src/Carousel/Carousel.tsx
  lib/src/Carousel/CarouselIndicators.tsx
  lib/src/Carousel/CarouselItem.tsx
  lib/src/Chip/Chip.tsx
  lib/src/CloseButton/CloseButton.tsx
  lib/src/Collapse/Collapse.tsx
  lib/src/Datepicker/Datepicker.tsx
  lib/src/Image/Img.tsx
  lib/src/ImageCropper/ImageCropper.tsx
  lib/src/Loader/Loader.tsx
  lib/src/Modal/Modal.tsx
  lib/src/Notification/Notification.tsx
  lib/src/Pagination/NumberedPagination.tsx
  lib/src/Pagination/Page.tsx
  lib/src/Pagination/Pagination.tsx
  lib/src/ProgressBar/ProgressBar.tsx
  lib/src/RadioButton/RadioButton.tsx
  lib/src/RadioButton/RadioGroup.tsx
  lib/src/Rating/Rating.tsx
  lib/src/Slider/Slider.tsx
  lib/src/StepTracker/StepTracker.tsx
  lib/src/Stepper/Stepper.tsx
  lib/src/Table/Table.tsx
  lib/src/Table/parts/TableBody.tsx
  lib/src/Table/parts/TableCell.tsx
  lib/src/Table/parts/TableHeader.tsx
  lib/src/Table/parts/TableHeaderCell.tsx
  lib/src/Table/parts/TableRow.tsx
  lib/src/Tabs/Tabs.tsx
  lib/src/TextLabel/TextLabel.tsx
  lib/src/Textarea/Textarea.tsx
  lib/src/Textbox/Textbox.tsx
  lib/src/Timeline/Timeline.tsx
  lib/src/Timeline/TimelineItem.tsx
  lib/src/Toggle/Toggle.tsx
  lib/src/ToggleSelector/ToggleSelector.tsx
Labels: 🙅‍♂️ Wontfix, 🚧 Refactor

#546 Docs/dynamic form docs entry
  docs/src/components/SideMenu.tsx
  docs/src/pages/docs/dynamic-forms.tsx
  docs/src/styles/playground.scss
  lib/src/hooks/useDynamicForm.tsx
Labels: 📚 Documentation

#556 fix(dynamic-forms): dynamic form should render null check fix
  lib/src/hooks/useDynamicForm.tsx
Labels: 🐛 Bug

#558 docs(dynamic-forms): fix radio button value access
  docs/src/pages/docs/button.tsx
  docs/src/pages/docs/buttongroup.tsx
  docs/src/pages/docs/carousel.tsx
  docs/src/pages/docs/checkbox.tsx
  docs/src/pages/docs/feedbackindicator.tsx
  docs/src/pages/docs/image.tsx
  docs/src/pages/docs/loader.tsx
  docs/src/pages/docs/modal.tsx
  docs/src/pages/docs/notification.tsx
  docs/src/pages/docs/pagination.tsx
  docs/src/pages/docs/radiobutton.tsx
  docs/src/pages/docs/slider.tsx
  docs/src/pages/docs/stepper.tsx
  docs/src/pages/docs/textarea.tsx
  docs/src/pages/docs/textbox.tsx
  docs/src/pages/docs/timeline.tsx
  docs/src/pages/docs/toggle-selector.tsx
Labels: 🐛 Bug, 📚 Documentation

#561 fix(build): fix build and circular dependency
  lib/rollup.config.js
  lib/src/Accordion/Accordion.tsx
  lib/src/Accordion/AccordionItem.tsx
  lib/src/Carousel/Carousel.tsx
  lib/src/Carousel/CarouselIndicators.test.tsx
  lib/src/Carousel/CarouselNavs.test.tsx
  lib/src/Checkbox/Checkbox.tsx
  lib/src/Dropdown/CustomDropdownItem.tsx
  lib/src/Dropdown/Dropdown.tsx
  lib/src/RadioButton/RadioButton.tsx
  lib/src/Stepper/Stepper.tsx
  lib/src/Table/parts/TableRow.tsx
  lib/src/Textarea/Textarea.tsx
  lib/src/Textbox/Textbox.tsx
  lib/src/Toggle/Toggle.tsx
  lib/src/ToggleSelector/ToggleSelector.tsx
  lib/src/ToggleSelector/ToggleSelectorItem.tsx
  lib/src/Tooltip/Tooltip.tsx
  lib/src/hooks/useDynamicForm.tsx
Labels: 🐛 Bug
