Repository sebgroup/react-components, pull requests merged in 2022-01, with the labels that each got.

#688 refactor(notification): improve accessibility
  docs/src/pages/docs/notification.tsx
  lib/src/Notification/Notification.tsx
  lib/src/Notification/notification.scss
Labels: 🚧 Refactor

#678 Refactor/tab
  docs/src/components/DocsAPIs.tsx
  docs/src/components/DocsPlaygroud.tsx
  docs/src/pages/docs/tabs.tsx
  docs/src/styles/playground.scss
  lib/src/Tabs/TabItem.tsx
  lib/src/Tabs/Tabs.test.tsx
  lib/src/Tabs/Tabs.tsx
  lib/src/utils/keyboardHelper.ts
Labels: 🔨 Enhancement, 📚 Documentation, 🚧 Refactor

#694 build(package.json): remove exports path
  package.json
Labels: 🐛 Bug

#695 refactor(tooltip): fix tooltip bug and improve accessibility
  docs/src/pages/docs/tooltip.tsx
  lib/src/Tooltip/Tooltip.tsx
  lib/src/Tooltip/useOverlay.tsx
Labels: 🐛 Bug, 🚧 Refactor

#691 refactor(modal): restructure keyboard support
  docs/src/pages/docs/modal.tsx
  lib/src/Modal/Modal.test.tsx
  lib/src/Modal/Modal.tsx
Labels: 🚧 Refactor

#692 refactor(sortable-list): improve sortable list accessibility
  lib/src/SortableList/SortableList.test.tsx
  lib/src/SortableList/SortableList.tsx
  lib/src/SortableList/sortable-list.scss
Labels: 🚧 Refactor

#697 feat(dynamic-form): removes logic for conditional rendering in favour…
  docs/src/pages/docs/accordion.tsx
  docs/src/pages/docs/breadcrumb.tsx
  docs/src/pages/docs/button.tsx
  docs/src/pages/docs/buttongroup.tsx
  docs/src/pages/docs/carousel.tsx
  docs/src/pages/docs/checkbox.tsx
  docs/src/pages/docs/closebutton.tsx
  docs/src/pages/docs/datepicker.tsx
  docs/src/pages/docs/dropdown.tsx
  docs/src/pages/docs/dynamic-forms.tsx
  docs/src/pages/docs/feedbackindicator.tsx
  docs/src/pages/docs/image.tsx
  docs/src/pages/docs/imagecropper.tsx
  docs/src/pages/docs/loader.tsx
  docs/src/pages/docs/modal.tsx
  docs/src/pages/docs/notification.tsx
  docs/src/pages/docs/pagination.tsx
  docs/src/pages/docs/progressbar.tsx
  docs/src/pages/docs/radiobutton.tsx
  docs/src/pages/docs/rating.tsx
  docs/src/pages/docs/slider.tsx
  docs/src/pages/docs/sortable-list.tsx
  docs/src/pages/docs/stepper.tsx
  docs/src/pages/docs/steptracker.tsx
  docs/src/pages/docs/table.tsx
  docs/src/pages/docs/tabs.tsx
  docs/src/pages/docs/textarea.tsx
  docs/src/pages/docs/textbox.tsx
  docs/src/pages/docs/textlabel.tsx
  docs/src/pages/docs/timeline.tsx
  docs/src/pages/docs/timer.tsx
  docs/src/pages/docs/toggle-selector.tsx
  docs/src/pages/docs/toggle.tsx
  docs/src/pages/docs/tooltip.tsx
  docs/src/pages/docs/video.tsx
  lib/src/hooks/useDynamicForm.test.tsx
  lib/src/hooks/useDynamicForm.tsx
Labels: 🔨 Enhancement
