Repository sebgroup/react-components, pull requests merged in 2022-12, with the labels that each got.

#770 feat: add field instruction to text box component
  .github/CODEOWNERS
  docs/src/pages/docs/textbox.tsx
  lib/src/Textbox/Textbox.test.tsx
  lib/src/Textbox/Textbox.tsx
  lib/src/Textbox/textbox.scss
Labels: 🔨 Enhancement

#778 fix: 🐛 use 'dependencies' key instead for typescript
  docs/src/components/TechStack.tsx
Labels: 🐛 Bug

#779 release
  docs/src/components/TechStack.tsx
Labels: 🚀 Release

#780 feat: table list
  docs/src/pages/docs/tablelist.tsx
  docs/static/components-list.json
  lib/src/TableList/TableList.test.tsx
  lib/src/TableList/TableList.tsx
  lib/src/TableList/TableListItem.test.tsx
  lib/src/TableList/TableListItem.tsx
  lib/src/TableList/index.ts
  lib/src/TableList/table-list.scss
  lib/src/index.json
  lib/src/index.ts
Labels: 🔨 Enhancement

#784 fix: add inline support to table list item
  docs/src/pages/docs/tablelist.tsx
  lib/src/TableList/TableListItem.test.tsx
  lib/src/TableList/TableListItem.tsx
  lib/src/TableList/table-list.scss
Labels: 🔨 Enhancement
